import {
  cloudflareDeliveryUrl,
  isCloudflareImagesEnabled,
} from "@/lib/cloudflare-images";

/**
 * Site image catalog.
 * Primary delivery: Cloudflare Images (imagedelivery.net).
 * Backup: git-tracked files under /public/images (Vercel next/image).
 */

export const IMAGE_KEYS = [
  "las-vegas-homes-hero",
  "summerlin",
  "henderson",
  "the-ridges",
  "green-valley",
  "skye-canyon",
  "southern-highlands",
  "centennial-hills",
  "inspirada",
  "mountains-edge",
  "north-las-vegas",
  "active-adult-clubhouse",
  "new-construction",
  "office-lake-mead",
  "consultation-office",
  "buyer-front-door",
  "seller-kitchen",
  "investment-rentals",
  "relocation",
  "market-skyline",
  "first-time-buyer",
  "golf-course",
  "lake-las-vegas",
  "luxury-pool-terrace",
  "macdonald-highlands",
  "red-rock-canyon",
  "strip-highrise",
  "guard-gated-entry",
  "anthem-henderson",
  "lock-and-leave-condo",
  "move-up-home",
  "downsizing-patio",
  "home-valuation-cma",
  "real-estate-services",
  "seller-sold-home",
  "divorce-probate-desk",
  "faq-consultation",
  "why-bhhs-office",
] as const;

export type ImageKey = (typeof IMAGE_KEYS)[number];

export interface SiteImageAsset {
  key: ImageKey;
  /** Git-backed public path (backup + origin upload source). */
  src: string;
  /** Cloudflare Images custom ID (same as git path without leading slash / extension). */
  cloudflareId: string;
  alt: string;
  width: number;
  height: number;
  heading: string;
}

export const imageCatalog: Record<ImageKey, SiteImageAsset> = {
  "las-vegas-homes-hero": {
    key: "las-vegas-homes-hero",
    src: "/images/hero/las-vegas-homes-hero.webp",
    cloudflareId: "hero/las-vegas-homes-hero",
    alt: "Las Vegas Valley homes with desert landscaping and mountain views at sunset",
    width: 1376,
    height: 768,
    heading: "Las Vegas Homes for Sale",
  },
  summerlin: {
    key: "summerlin",
    src: "/images/neighborhoods/summerlin.webp",
    cloudflareId: "neighborhoods/summerlin",
    alt: "Summerlin Las Vegas homes near Red Rock Canyon trails and desert parks",
    width: 1376,
    height: 768,
    heading: "Summerlin Homes",
  },
  henderson: {
    key: "henderson",
    src: "/images/neighborhoods/henderson.webp",
    cloudflareId: "neighborhoods/henderson",
    alt: "Henderson Nevada residential street with palm trees and mountain backdrop",
    width: 1376,
    height: 768,
    heading: "Henderson Homes",
  },
  "the-ridges": {
    key: "the-ridges",
    src: "/images/neighborhoods/the-ridges.webp",
    cloudflareId: "neighborhoods/the-ridges",
    alt: "Luxury custom estate with infinity pool overlooking the Las Vegas Valley",
    width: 1376,
    height: 768,
    heading: "Luxury Homes in The Ridges",
  },
  "green-valley": {
    key: "green-valley",
    src: "/images/neighborhoods/green-valley.webp",
    cloudflareId: "neighborhoods/green-valley",
    alt: "Green Valley Henderson golf course community with homes along the fairway",
    width: 1376,
    height: 768,
    heading: "Green Valley Homes",
  },
  "skye-canyon": {
    key: "skye-canyon",
    src: "/images/neighborhoods/skye-canyon.webp",
    cloudflareId: "neighborhoods/skye-canyon",
    alt: "Skye Canyon Northwest Las Vegas homes with desert mountain views",
    width: 1376,
    height: 768,
    heading: "Skye Canyon Homes",
  },
  "southern-highlands": {
    key: "southern-highlands",
    src: "/images/neighborhoods/southern-highlands.webp",
    cloudflareId: "neighborhoods/southern-highlands",
    alt: "Southern Highlands Las Vegas golf community and custom homes on a ridge",
    width: 1376,
    height: 768,
    heading: "Southern Highlands Homes",
  },
  "centennial-hills": {
    key: "centennial-hills",
    src: "/images/neighborhoods/centennial-hills.webp",
    cloudflareId: "neighborhoods/centennial-hills",
    alt: "Centennial Hills walking trail with homes and northwest Las Vegas mountains",
    width: 1376,
    height: 768,
    heading: "Centennial Hills Homes",
  },
  inspirada: {
    key: "inspirada",
    src: "/images/neighborhoods/inspirada.webp",
    cloudflareId: "neighborhoods/inspirada",
    alt: "Inspirada Henderson resort-style community pool and modern homes",
    width: 1376,
    height: 768,
    heading: "Inspirada Homes",
  },
  "mountains-edge": {
    key: "mountains-edge",
    src: "/images/neighborhoods/mountains-edge.webp",
    cloudflareId: "neighborhoods/mountains-edge",
    alt: "Mountains Edge Southwest Las Vegas homes beside desert mountain wilderness",
    width: 1376,
    height: 768,
    heading: "Mountains Edge Homes",
  },
  "north-las-vegas": {
    key: "north-las-vegas",
    src: "/images/neighborhoods/north-las-vegas.webp",
    cloudflareId: "neighborhoods/north-las-vegas",
    alt: "North Las Vegas new construction homes with desert mountain backdrop",
    width: 1376,
    height: 768,
    heading: "North Las Vegas Homes",
  },
  "active-adult-clubhouse": {
    key: "active-adult-clubhouse",
    src: "/images/hero/active-adult-clubhouse.webp",
    cloudflareId: "hero/active-adult-clubhouse",
    alt: "55-plus community clubhouse and resort pool in the Las Vegas Valley",
    width: 1376,
    height: 768,
    heading: "55+ Communities",
  },
  "new-construction": {
    key: "new-construction",
    src: "/images/hero/new-construction.webp",
    cloudflareId: "hero/new-construction",
    alt: "Newly completed desert production home in Las Vegas with mountain views",
    width: 1376,
    height: 768,
    heading: "New Construction",
  },
  "office-lake-mead": {
    key: "office-lake-mead",
    src: "/images/office/office-lake-mead.webp",
    cloudflareId: "office/office-lake-mead",
    alt: "Berkshire Hathaway HomeServices Nevada Properties office near Lake Mead Boulevard in Las Vegas",
    width: 1376,
    height: 768,
    heading: "Contact Dr. Jan Duffy",
  },
  "consultation-office": {
    key: "consultation-office",
    src: "/images/office/consultation-office.webp",
    cloudflareId: "office/consultation-office",
    alt: "Real estate consultation table with listing packets in a Las Vegas office",
    width: 1024,
    height: 768,
    heading: "Meet Dr. Jan Duffy",
  },
  "buyer-front-door": {
    key: "buyer-front-door",
    src: "/images/services/buyer-front-door.webp",
    cloudflareId: "services/buyer-front-door",
    alt: "Front door of a Las Vegas desert home with house keys ready for a buyer",
    width: 1376,
    height: 768,
    heading: "Home Buying",
  },
  "seller-kitchen": {
    key: "seller-kitchen",
    src: "/images/services/seller-kitchen.webp",
    cloudflareId: "services/seller-kitchen",
    alt: "Staged luxury kitchen in a Las Vegas home prepared for listing photos",
    width: 1376,
    height: 768,
    heading: "Home Selling",
  },
  "investment-rentals": {
    key: "investment-rentals",
    src: "/images/services/investment-rentals.webp",
    cloudflareId: "services/investment-rentals",
    alt: "Row of well-maintained Las Vegas single-family rental homes",
    width: 1376,
    height: 768,
    heading: "Investment Properties",
  },
  relocation: {
    key: "relocation",
    src: "/images/services/relocation.webp",
    cloudflareId: "services/relocation",
    alt: "Moving truck at a Las Vegas suburban home during a relocation",
    width: 1376,
    height: 768,
    heading: "Relocation to Las Vegas",
  },
  "market-skyline": {
    key: "market-skyline",
    src: "/images/hero/market-skyline.webp",
    cloudflareId: "hero/market-skyline",
    alt: "Las Vegas Valley rooftops at dusk with the Strip skyline on the horizon",
    width: 1376,
    height: 768,
    heading: "Las Vegas Market Report",
  },
  "first-time-buyer": {
    key: "first-time-buyer",
    src: "/images/services/first-time-buyer.webp",
    cloudflareId: "services/first-time-buyer",
    alt: "Approachable single-story Las Vegas home suited for first-time buyers",
    width: 1376,
    height: 768,
    heading: "First-Time Home Buyers",
  },
  "golf-course": {
    key: "golf-course",
    src: "/images/neighborhoods/golf-course.webp",
    cloudflareId: "neighborhoods/golf-course",
    alt: "Championship desert golf course in Las Vegas with mountain views at golden hour",
    width: 1376,
    height: 768,
    heading: "Golf Course Communities",
  },
  "lake-las-vegas": {
    key: "lake-las-vegas",
    src: "/images/neighborhoods/lake-las-vegas.webp",
    cloudflareId: "neighborhoods/lake-las-vegas",
    alt: "Lake Las Vegas waterfront and resort architecture at dusk in Henderson",
    width: 1376,
    height: 768,
    heading: "Lake Las Vegas Homes",
  },
  "luxury-pool-terrace": {
    key: "luxury-pool-terrace",
    src: "/images/neighborhoods/luxury-pool-terrace.webp",
    cloudflareId: "neighborhoods/luxury-pool-terrace",
    alt: "Luxury Las Vegas estate pool terrace at twilight with valley lights on the horizon",
    width: 1376,
    height: 768,
    heading: "Luxury Pool Estates",
  },
  "macdonald-highlands": {
    key: "macdonald-highlands",
    src: "/images/neighborhoods/macdonald-highlands.webp",
    cloudflareId: "neighborhoods/macdonald-highlands",
    alt: "MacDonald Highlands Henderson luxury homes on a ridge with valley views at dusk",
    width: 1376,
    height: 768,
    heading: "MacDonald Highlands",
  },
  "red-rock-canyon": {
    key: "red-rock-canyon",
    src: "/images/neighborhoods/red-rock-canyon.webp",
    cloudflareId: "neighborhoods/red-rock-canyon",
    alt: "Red Rock Canyon sandstone cliffs west of Summerlin Las Vegas at golden hour",
    width: 1376,
    height: 768,
    heading: "Red Rock Canyon",
  },
  "strip-highrise": {
    key: "strip-highrise",
    src: "/images/neighborhoods/strip-highrise.webp",
    cloudflareId: "neighborhoods/strip-highrise",
    alt: "Las Vegas Strip high-rise condominium towers at twilight",
    width: 1376,
    height: 768,
    heading: "Strip High-Rise Condos",
  },
  "guard-gated-entry": {
    key: "guard-gated-entry",
    src: "/images/neighborhoods/guard-gated-entry.webp",
    cloudflareId: "neighborhoods/guard-gated-entry",
    alt: "Guard-gated entry to a luxury Las Vegas community with desert landscaping",
    width: 1376,
    height: 768,
    heading: "Guard-Gated Communities",
  },
  "anthem-henderson": {
    key: "anthem-henderson",
    src: "/images/neighborhoods/anthem-henderson.webp",
    cloudflareId: "neighborhoods/anthem-henderson",
    alt: "Anthem Henderson hillside homes with McCullough Range views at sunset",
    width: 1376,
    height: 768,
    heading: "Anthem Henderson",
  },
  "lock-and-leave-condo": {
    key: "lock-and-leave-condo",
    src: "/images/services/lock-and-leave-condo.webp",
    cloudflareId: "services/lock-and-leave-condo",
    alt: "Lock-and-leave Las Vegas condominium balcony overlooking the valley",
    width: 1376,
    height: 768,
    heading: "Lock-and-Leave Condos",
  },
  "move-up-home": {
    key: "move-up-home",
    src: "/images/services/move-up-home.webp",
    cloudflareId: "services/move-up-home",
    alt: "Larger two-story Las Vegas move-up home with desert landscaping and mountain views",
    width: 1376,
    height: 768,
    heading: "Move-Up Homes",
  },
  "downsizing-patio": {
    key: "downsizing-patio",
    src: "/images/services/downsizing-patio.webp",
    cloudflareId: "services/downsizing-patio",
    alt: "Single-story Las Vegas patio home with low-maintenance desert landscaping",
    width: 1376,
    height: 768,
    heading: "Downsizing",
  },
  "home-valuation-cma": {
    key: "home-valuation-cma",
    src: "/images/services/home-valuation-cma.webp",
    cloudflareId: "services/home-valuation-cma",
    alt: "Home valuation packets and floor plan review on a staged Las Vegas kitchen island",
    width: 1376,
    height: 768,
    heading: "Home Valuation",
  },
  "real-estate-services": {
    key: "real-estate-services",
    src: "/images/services/real-estate-services.webp",
    cloudflareId: "services/real-estate-services",
    alt: "Las Vegas real estate consultation table with listing packets and house keys",
    width: 1376,
    height: 768,
    heading: "Las Vegas Real Estate Services",
  },
  "seller-sold-home": {
    key: "seller-sold-home",
    src: "/images/services/seller-sold-home.webp",
    cloudflareId: "services/seller-sold-home",
    alt: "Las Vegas suburban home with a sold yard sign and packed moving boxes on the porch",
    width: 1376,
    height: 768,
    heading: "Relocation Home Sales",
  },
  "divorce-probate-desk": {
    key: "divorce-probate-desk",
    src: "/images/office/divorce-probate-desk.webp",
    cloudflareId: "office/divorce-probate-desk",
    alt: "Quiet Las Vegas office desk with legal files prepared for a discreet home sale",
    width: 1376,
    height: 768,
    heading: "Divorce & Probate",
  },
  "faq-consultation": {
    key: "faq-consultation",
    src: "/images/office/faq-consultation.webp",
    cloudflareId: "office/faq-consultation",
    alt: "Las Vegas real estate office ready for a buyer and seller question session",
    width: 1376,
    height: 768,
    heading: "Frequently Asked Questions",
  },
  "why-bhhs-office": {
    key: "why-bhhs-office",
    src: "/images/office/why-bhhs-office.webp",
    cloudflareId: "office/why-bhhs-office",
    alt: "Berkshire Hathaway HomeServices Nevada Properties office interior in Las Vegas",
    width: 1376,
    height: 768,
    heading: "Why Choose Berkshire Hathaway HomeServices",
  },
};

const HEADING_IMAGE_MAP: Array<{ pattern: RegExp; key: ImageKey }> = [
  { pattern: /lake las vegas|del webb/i, key: "lake-las-vegas" },
  { pattern: /macdonald/i, key: "macdonald-highlands" },
  { pattern: /red rock/i, key: "red-rock-canyon" },
  { pattern: /strip|high-?rise|highrise/i, key: "strip-highrise" },
  { pattern: /lock.?and.?leave/i, key: "lock-and-leave-condo" },
  { pattern: /next chapter|move.?up|upgrade path|your equity/i, key: "move-up-home" },
  { pattern: /difficult situation|divorce|probate|expert guidance/i, key: "divorce-probate-desk" },
  { pattern: /guard.?gated|gated/i, key: "guard-gated-entry" },
  { pattern: /anthem|solera/i, key: "anthem-henderson" },
  { pattern: /golf|siena/i, key: "golf-course" },
  { pattern: /summerlin/i, key: "summerlin" },
  { pattern: /ridges/i, key: "the-ridges" },
  { pattern: /green valley/i, key: "green-valley" },
  { pattern: /skye canyon/i, key: "skye-canyon" },
  { pattern: /southern highlands/i, key: "southern-highlands" },
  { pattern: /centennial/i, key: "centennial-hills" },
  { pattern: /inspirada/i, key: "inspirada" },
  { pattern: /mountains.?edge|mountain.?s edge/i, key: "mountains-edge" },
  { pattern: /north las vegas|aliante/i, key: "north-las-vegas" },
  { pattern: /henderson/i, key: "henderson" },
  { pattern: /55\+|sun city|trilogy|heritage|active adult/i, key: "active-adult-clubhouse" },
  { pattern: /new construction|builder/i, key: "new-construction" },
  { pattern: /ascaya|summit club/i, key: "luxury-pool-terrace" },
  { pattern: /luxury|\$1m|pool terrace|(?<!real )estate/i, key: "luxury-pool-terrace" },
  { pattern: /faq|frequently asked/i, key: "faq-consultation" },
  { pattern: /why choose|why .{0,24}berkshire|bhhs advantage|unmatched trust|ethical|financial strength|proven results|trusted (brand|expertise)/i, key: "why-bhhs-office" },
  { pattern: /global.{0,12}network|worldwide/i, key: "relocation" },
  { pattern: /marketing|pricing strategy/i, key: "seller-kitchen" },
  { pattern: /simplify|downsiz/i, key: "downsizing-patio" },
  { pattern: /worth|valuation|cma/i, key: "home-valuation-cma" },
  { pattern: /real estate services|core real estate|specialized (real estate|guidance|services)|areas of specialization/i, key: "real-estate-services" },
  { pattern: /new opportunity|handle your sale/i, key: "seller-sold-home" },
  { pattern: /invest|rental|cap rate|1031|condo/i, key: "investment-rentals" },
  { pattern: /relocat|moving|california/i, key: "relocation" },
  { pattern: /first.?home|first.?time|first time|single-story/i, key: "first-time-buyer" },
  { pattern: /sell|listing/i, key: "seller-kitchen" },
  { pattern: /buy|buyer representation/i, key: "buyer-front-door" },
  { pattern: /market|insight|report|update/i, key: "market-skyline" },
  { pattern: /contact|office|hours|get in touch/i, key: "office-lake-mead" },
  { pattern: /about|meet|why work|consultation/i, key: "consultation-office" },
  { pattern: /dr\.?\s*jan|jan duffy/i, key: "office-lake-mead" },
];

export function imageForHeading(heading: string): SiteImageAsset {
  for (const entry of HEADING_IMAGE_MAP) {
    if (entry.pattern.test(heading)) {
      return imageCatalog[entry.key];
    }
  }
  return imageCatalog["las-vegas-homes-hero"];
}

export function getImageSrc(asset: SiteImageAsset): string {
  if (isCloudflareImagesEnabled()) {
    return cloudflareDeliveryUrl(asset.cloudflareId);
  }
  return asset.src;
}

export function assertNeverImage(key: never): never {
  throw new Error(`Unhandled image key: ${String(key)}`);
}
